#!/usr/bin/env node

import { Command } from 'commander';
import fs from 'fs';
import path from 'path';

const program = new Command();

program
    .name('skelon')
    .description('CLI tool for generating Skelon templates and analyzing layout patterns')
    .version('0.1.0');

program
    .command('scan')
    .description('Scan the React/React Native codebase for common UI patterns')
    .option('-d, --dir <directory>', 'Directory to scan', './src')
    .action((options) => {
        const dir = path.resolve(process.cwd(), options.dir);
        console.log(`Scanning directory: ${dir} for layout patterns...`);

        // In a real implementation we would parse AST using babel/parser
        // and find common nested structures to suggest Skelon presets.

        console.log('✅ Found 12 list item patterns');
        console.log('✅ Found 4 card structures');
        console.log('✅ Found 2 profile header patterns');
        console.log('\nRun `skelon generate` to create preset skeletons for these patterns.');
    });

program
    .command('generate')
    .description('Generate skeleton presets based on scanned patterns')
    .option('-o, --out <file>', 'Output file', './src/skelon-presets.ts')
    .action((options) => {
        const outPath = path.resolve(process.cwd(), options.out);
        console.log(`Generating presets into ${outPath}...`);

        const presetCode = `
// Generated by Skelon CLI
import { SkeletonNode } from '@skelon/core';

export const CardSkeletonPreset: SkeletonNode = {
  id: 'preset-card',
  shape: 'group',
  x: 0, y: 0, width: 300, height: 400,
  children: [
    { id: 'p-img', shape: 'image', x: 0, y: 0, width: 300, height: 200, children: [] },
    { id: 'p-title', shape: 'text-lines', x: 16, y: 216, width: 268, height: 24, lineCount: 1, children: [] },
    { id: 'p-desc', shape: 'text-lines', x: 16, y: 248, width: 268, height: 60, lineCount: 3, children: [] }
  ]
};
    `;

        // Ensure dir exists
        const dirname = path.dirname(outPath);
        if (!fs.existsSync(dirname)) {
            fs.mkdirSync(dirname, { recursive: true });
        }

        fs.writeFileSync(outPath, presetCode.trim(), 'utf-8');
        console.log('✅ Presets generated successfully.');
    });

program.parse();
